/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

/**
 *
 * @author Tito
 */
public class GrafikPenjualan extends javax.swing.JPanel {

    /**
     * Creates new form LaporanTerlaris
     */
    public GrafikPenjualan() {
        initComponents();
        
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(spinnerMulai, "dd-MM-yyyy");
        spinnerMulai.setEditor(editor1);

        // Format Spinner 2
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(spinnerSampai, "dd-MM-yyyy");
        spinnerSampai.setEditor(editor2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        spinnerMulai = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerSampai = new javax.swing.JSpinner();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlGrafik = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFIK PENJUALAN");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        spinnerMulai.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PILIH PERIODE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("S/D");

        spinnerSampai.setModel(new javax.swing.SpinnerDateModel());

        btnCari.setBackground(new java.awt.Color(102, 102, 102));
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(spinnerSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(btnCari)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlGrafik.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(pnlGrafik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        loadGrafik();
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlGrafik;
    private javax.swing.JSpinner spinnerMulai;
    private javax.swing.JSpinner spinnerSampai;
    // End of variables declaration//GEN-END:variables

    private void loadGrafik() {
        // 1. Bersihkan Grafik Lama
        pnlGrafik.removeAll();
        pnlGrafik.revalidate();
        pnlGrafik.repaint();
        
        try {
            // Ambil Tanggal dari Spinner
            java.util.Date date1 = (java.util.Date) spinnerMulai.getValue();
            java.util.Date date2 = (java.util.Date) spinnerSampai.getValue();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl1 = sdf.format(date1);
            String tgl2 = sdf.format(date2);

            java.sql.Connection K = com.motorin.db.koneksi.Go();
            java.sql.Statement S = K.createStatement();

            // --- STEP A: CARI NILAI TERTINGGI (Untuk Skala Grafik) ---
            // Kita butuh tahu hari apa yang omsetnya paling gede biar jadi patokan 100%
            String sqlMax = "SELECT MAX(total_harian) as top_skor FROM " +
                            "(SELECT sum(total_harga) as total_harian FROM transaksi " +
                            "WHERE tanggal BETWEEN '"+tgl1+"' AND '"+tgl2+"' GROUP BY tanggal) as tabel_dummy";
            
            java.sql.ResultSet RMax = S.executeQuery(sqlMax);
            double maxOmset = 1; // Default biar gak error bagi 0
            if (RMax.next()) {
                maxOmset = RMax.getDouble("top_skor");
            }
            
            // --- STEP B: AMBIL DATA OMSET PER HARI ---
            String sql = "SELECT tanggal, SUM(total_harga) as omset " +
                         "FROM transaksi " +
                         "WHERE tanggal BETWEEN '"+tgl1+"' AND '"+tgl2+"' " +
                         "GROUP BY tanggal ORDER BY tanggal ASC";
            
            java.sql.ResultSet R = S.executeQuery(sql);

            // --- STEP C: LUKIS GRAFIK (Looping) ---
            while (R.next()) {
                String tanggal = R.getString("tanggal");
                double omset = R.getDouble("omset");
                
                // Hitung Persentase panjang bar
                int persentase = (int) ((omset / maxOmset) * 100);
                
                // Format Uang (Rp ...)
                String duitStr = String.format("Rp %,.0f", omset).replace(',', '.');
                
                // BIKIN KOMPONEN VISUAL SECARA MANUAL (CODING)
                javax.swing.JPanel panelBaris = new javax.swing.JPanel();
                panelBaris.setLayout(new java.awt.BorderLayout(10, 10));
                panelBaris.setBackground(java.awt.Color.WHITE);
                panelBaris.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                
                // 1. Label Tanggal (Kiri)
                javax.swing.JLabel lblTgl = new javax.swing.JLabel(tanggal);
                lblTgl.setPreferredSize(new java.awt.Dimension(80, 20)); // Lebar label tanggal
                
                // 2. Bar Grafik (Tengah)
                javax.swing.JProgressBar bar = new javax.swing.JProgressBar();
                bar.setValue(persentase); 
                bar.setString(duitStr); // Tulis nominal uang di dalam bar
                bar.setStringPainted(true);
                bar.setForeground(new java.awt.Color(51, 153, 255)); // Warna Biru
                
                // Tambahkan ke Panel Baris
                panelBaris.add(lblTgl, java.awt.BorderLayout.WEST);
                panelBaris.add(bar, java.awt.BorderLayout.CENTER);
                
                // Tambahkan Panel Baris ke Panel Utama Grafik
                pnlGrafik.add(panelBaris);
            }
            
            // Update Tampilan biar muncul
            pnlGrafik.revalidate(); 
            pnlGrafik.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }


}
