/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

/**
 *
 * @author Tito
 */
public class LaporanTerlaris extends javax.swing.JPanel {

    /**
     * Creates new form LaporanTerlaris
     */
    public LaporanTerlaris() {
        initComponents();
        
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(spinnerMulai, "dd-MM-yyyy");
        spinnerMulai.setEditor(editor1);

        // Format Spinner 2
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(spinnerSampai, "dd-MM-yyyy");
        spinnerSampai.setEditor(editor2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_laporanTerlaris = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        spinnerMulai = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerSampai = new javax.swing.JSpinner();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        lbl_laporanTerlaris.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_laporanTerlaris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_laporanTerlaris.setText("LAPORAN PRODUK TERLARIS");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        spinnerMulai.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PILIH PERIODE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("S/D");

        spinnerSampai.setModel(new javax.swing.SpinnerDateModel());

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(spinnerSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(btnCari)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "no", "merk", "tipe", "terjual", "pendapatan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_laporanTerlaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_laporanTerlaris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        loadDataTerlaris();
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_laporanTerlaris;
    private javax.swing.JSpinner spinnerMulai;
    private javax.swing.JSpinner spinnerSampai;
    // End of variables declaration//GEN-END:variables

    private void loadDataTerlaris() {
        try {
            // 1. Ambil Tanggal dari Spinner
            java.util.Date date1 = (java.util.Date) spinnerMulai.getValue();
            java.util.Date date2 = (java.util.Date) spinnerSampai.getValue();
            
            // 2. Format Tanggal
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tgl1 = sdf.format(date1);
            String tgl2 = sdf.format(date2);

            // 3. Reset Tabel
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // 4. Koneksi & Query
            java.sql.Connection K = com.motorin.db.koneksi.Go();
            java.sql.Statement S = K.createStatement();

            // Query: Gabung tabel barang -> Hitung Total Qty -> Filter Tanggal -> Urutkan Terlaris
            String sql = "SELECT b.nama_barang, b.kategori, "
                       + "SUM(dt.jumlah) as total_qty, "
                       + "SUM(dt.subtotal) as total_uang " 
                       + "FROM detail_transaksi dt " 
                       + "JOIN transaksi t ON t.id_transaksi = dt.id_transaksi " 
                       + "JOIN barang b ON b.id_barang = dt.id_barang " // Sesuaikan ke tabel barang
                       + "WHERE t.tanggal BETWEEN '" + tgl1 + "' AND '" + tgl2 + "' " 
                       + "GROUP BY b.id_barang " // Group berdasarkan id_barang
                       + "ORDER BY total_qty DESC";// DESC = Besar ke Kecil

            java.sql.ResultSet R = S.executeQuery(sql);

            // 5. Isi Tabel
            int no = 1;
            while (R.next()) {
                // Sesuaikan: Ambil kolom 'nama_barang' dari alias b di SQL
                String nama_barang = R.getString("nama_barang"); 

                // Sesuaikan: Ambil kolom 'kategori'
                String kategori = R.getString("kategori"); 

                // Alias 'total_qty' tetap sama karena kita definisikan di SQL
                String qty = R.getString("total_qty");

                // Format Rupiah untuk 'total_uang'
                double duit = R.getDouble("total_uang");
                String duitStr = String.format("Rp %,.0f", duit).replace(',', '.');

                // Masukkan ke array sesuai urutan kolom tabel Anda
                Object[] data = {no++, nama_barang, kategori, qty, duitStr};
                model.addRow(data);

            }
            
            // Validasi jika kosong
            if (model.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada data penjualan di periode ini.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }


}
