/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

import Dialog.AddNewProduct;
import Dialog.DeleteProducts;
import Dialog.EditProducts;
import com.motorin.db.Products;
import com.motorin.db.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


public class ManageProducts extends javax.swing.JPanel {

    Products Pm;
    
    public ManageProducts() {
        initComponents();
        refreshDataProducts("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 585, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_barang", "nama_barang", "kategori", "stok", "harga_be;li", "harga_jual", "satuan", "tanggal_masuk"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 430));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Connection K = com.motorin.db.koneksi.Go(); 
        String Q = "SELECT * FROM barang"; 
        Statement S = K.createStatement();
        ResultSet R = S.executeQuery(Q);

        // --- CARI BAGIAN INI DI KODINGAN ANDA ---
        // Baris 167: ResultSet R = S.executeQuery(Q);

    while (R.next()) {
    String id = R.getString("id_barang");
    String nama_barang = R.getString("nama_barang");
    String kategori = R.getString("kategori");
    String stok = R.getString("stok");
    
    // Ambil harga sebagai Double agar bisa diformat (menghilangkan .00)
    double h_beli = R.getDouble("harga_beli");
    double h_jual = R.getDouble("harga_jual");
    
    // Ambil satuan sebagai String, BUKAN getDouble
    String satuan = R.getString("satuan"); 
    String tanggal_masuk = R.getString("tanggal_masuk");
    
    // Format agar angka rapi tanpa desimal
    String vBeli = String.format("%.0f", h_beli);
    String vJual = String.format("%.0f", h_jual);
    
    Object[] dataProduct = {id, nama_barang, kategori, stok, vBeli, vJual, satuan, tanggal_masuk};
    model.addRow(dataProduct);

}
        
        
        // ---------------------------------------

    } catch (Exception e) {
        // ...
    }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        jTable1.clearSelection();
        refreshDataProducts("");
        txtSearch.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DeleteProducts DP = new DeleteProducts(null, true);
    // Ganti .DP menjadi .DM agar sesuai dengan deklarasi di file tujuan
    DP.DM = Pm; 
    DP.setVisible(true);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        searchDataProducts();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int n = jTable1.getSelectedRow();
        if (n != -1) {
            btnEdit.setEnabled(true);
            btnHapus.setEnabled(true);
            //ekstraksi data
            Pm = new Products();
            String IDmtr = jTable1.getValueAt(n, 0).toString();
            int ID = Integer.valueOf(IDmtr);
            String nama_barang = jTable1.getValueAt(n, 1).toString();
            String kategori = jTable1.getValueAt(n, 2).toString();
            String stok = jTable1.getValueAt(n, 3).toString();
            String harga_jual = jTable1.getValueAt(n, 4).toString();
            String harga_beli = jTable1.getValueAt(n, 5).toString();
            String satuan = jTable1.getValueAt(n, 6).toString();
            String tanggal_masuk = jTable1.getValueAt(n, 7).toString();
            Pm.setId_barang(ID);
            Pm.setNama_barang(nama_barang);
            Pm.setKategori(kategori);
            Pm.setStok(stok);
            Pm.setHarga_jual(harga_jual);
            Pm.setHarga_beli(harga_beli);
            Pm.setSatuan(satuan);
            Pm.setTanggal_masuk(tanggal_masuk);

        
            
            
            
            try {
                java.sql.Connection K = com.motorin.db.koneksi.Go();
                java.sql.Statement S = K.createStatement();
                
                // Cari nama gambar berdasarkan ID
                String sql = "SELECT gambar FROM motorindong WHERE id_barang='" + IDmtr + "'";
                java.sql.ResultSet R = S.executeQuery(sql);
                
                if (R.next()) {
                    String namaFile = R.getString("gambar");
                    // Simpan info gambar ke objek Motor agar form Edit tahu
                    Pm.setGambar(namaFile); 
                }
            } catch (Exception e) {
                System.out.println("Gagal ambil gambar: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddNewProduct NM = new AddNewProduct(null, true);
    NM.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            EditProducts EM = new EditProducts(null, true);
            EM.M = Pm;
            EM.setVisible(true);
            refreshDataProducts("");
        }else {
           javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris dulu!");
        }
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

public static void refreshDataProducts(String w) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection K = koneksi.Go();
            String Q = "SELECT * FROM motorindong " + w;
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()) {
                String id = R.getString("id_barang");
                String nama_barang = R.getString("nama_barang");
                String kategori = R.getString("kategori");
                String stok = R.getString("stok");
                String harga_beli = R.getString("harga_beli");
                double harga_jual = R.getDouble("harga_jual");
                double satuan = R.getDouble("satuan");
                String tanggal_masuk = R.getString("tanggal_masuk");
                
                String vBeli = String.format("%.0f", harga_beli);
                String vJual = String.format("%.0f", harga_jual);
                
                Object[] dataProduct = {id, nama_barang, kategori, stok, vBeli, vJual, satuan, tanggal_masuk};
                model.addRow(dataProduct);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            
        }
    }
    private void searchDataProducts() {
        String key = txtSearch.getText();
        String where = " WHERE " 
            + "id_barang LIKE '%" + key + "%' OR "
            + "nama_barang LIKE '%" + key + "%' OR "
            + "kategori LIKE '%" + key + "%' OR "
            + "stok LIKE '%" + key + "%' OR "
            + "harga_beli LIKE '%" + key + "%' OR "
            + "harga_jual LIKE '%" + key + "%' OR "
            + "satuan LIKE '%" + key + "%' OR "
            + "tanggal_masuk LIKE '%" + key + "%'";
    refreshDataProducts(where);
    }
    
    

}
