/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

import static motorin.panel.KelolaProducts.refreshDataProducts;
import com.motorin.db.koneksi;
import com.motorin.db.Products;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adies
 */
public class ProdukTerjual extends javax.swing.JPanel {
     Products Pm;
    /**
     * Creates new form ProdukTerjual
     */
    public ProdukTerjual() {
        initComponents();
        refreshDataMotor("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_motor", "merk", "tipe", "tahun", "warna", "harga", "stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUK TERJUAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int n = jTable1.getSelectedRow();
        if (n != -1) {
    
            //ekstraksi data
            Pm = new Products();
            String IDmtr = jTable1.getValueAt(n, 0).toString();
            
            String merk = jTable1.getValueAt(n, 1).toString();
            String tipe = jTable1.getValueAt(n, 2).toString();
            String tahun = jTable1.getValueAt(n, 3).toString();
            String warna = jTable1.getValueAt(n, 4).toString();
            String harga = jTable1.getValueAt(n, 5).toString();
            String stok = jTable1.getValueAt(n, 6).toString();
            int ID = 0;
            Pm.setId_barang(ID);
            String nama_barang = null;
            Pm.setNama_barang(nama_barang);
            String kategori = null;
            Pm.setKategori(kategori);
            Pm.setStok(stok);
            String harga_jual = null;
            Pm.setHarga_jual(harga_jual);
            String harga_beli = null;
            Pm.setHarga_beli(harga_beli);
            String satuan = null;
            Pm.setSatuan(satuan);
            String tanggal_masuk = null;
            Pm.setTanggal_masuk(tanggal_masuk);
            
            
            
            try {
                java.sql.Connection K = com.motorin.db.koneksi.Go();
                java.sql.Statement S = K.createStatement();
                
                // Cari nama gambar berdasarkan ID
                String sql = "SELECT gambar FROM motor WHERE id_motor='" + IDmtr + "'";
                java.sql.ResultSet R = S.executeQuery(sql);
                
                if (R.next()) {
                    String namaFile = R.getString("gambar");
                    // Simpan info gambar ke objek Motor agar form Edit tahu
                    Pm.setGambar(namaFile); 
                }
            } catch (Exception e) {
                System.out.println("Gagal ambil gambar: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public static void refreshDataMotor(String w) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection K = koneksi.Go();
            String Q = "SELECT * FROM motor" + w;
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()) {
                String id = R.getString("id_barang");
                String merk = R.getString("merk");
                String tipe = R.getString("tipe");
                String tahun = R.getString("tahun");
                String warna = R.getString("warna");
                String harga = R.getString("harga");
                String stok = R.getString("stok");
                Object[] datamotor = {id, merk, tipe, tahun, warna, harga, stok};
                model.addRow(datamotor);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            
        }
    }


}
