/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

import static motorin.panel.ManageProducts.refreshDataProducts;
import com.motorin.db.koneksi;
import com.motorin.db.Products;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adies
 */
public class ProdukTerjual extends javax.swing.JPanel {
     Products Pm;
    /**
     * Creates new form ProdukTerjual
     */
    public ProdukTerjual() {
        initComponents();
        refreshDataproducts("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_motor", "merk", "tipe", "tahun", "warna", "harga", "stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUK TERJUAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int n = jTable1.getSelectedRow();
        if (n != -1) {
    
            //ekstraksi data
            Pm = new Products();
            String IDmtr = jTable1.getValueAt(n, 0).toString();
            
            String id = jTable1.getValueAt(n, 0).toString();
            String nama = jTable1.getValueAt(n, 1).toString();
            String kategori = jTable1.getValueAt(n, 2).toString();
            String stok = jTable1.getValueAt(n, 3).toString();
            String harga_beli = jTable1.getValueAt(n, 4).toString(); // Variabel h_beli
            String harga_jual = jTable1.getValueAt(n, 5).toString(); // Variabel h_jual
            String satuan = jTable1.getValueAt(n, 6).toString();
            String tgl = jTable1.getValueAt(n, 7).toString();

            // Memasukkan data ke objek Pm (Products)
            Pm.setId_barang(Integer.parseInt(id));
            Pm.setNama_barang(nama);
            Pm.setKategori(kategori);
            Pm.setStok(stok);
            // Perbaikan: gunakan h_beli dan h_jual agar tidak error
            Pm.setHarga_beli(Double.parseDouble(h_beli));
            Pm.setHarga_jual(Double.parseDouble(h_jual)); 
            Pm.setSatuan(satuan);
            Pm.setTanggal_masuk(tgl);
            
            
            
            try {
                java.sql.Connection K = Bmj.util.Koneksi.Go();
                java.sql.Statement S = K.createStatement();
                
                // Cari nama gambar berdasarkan ID
                String sql = "SELECT gambar FROM barang WHERE id_barang='" + IDmtr + "'";
                java.sql.ResultSet R = S.executeQuery(sql);
                
                if (R.next()) {
                    String namaFile = R.getString("gambar");
                    // Simpan info gambar ke objek barang agar form Edit tahu
                    Pm.setGambar(namaFile); 
                }
            } catch (Exception e) {
                System.out.println("Gagal ambil gambar: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public static void refreshDataProducts(String w) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            // Membersihkan data lama di tabel
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection K = koneksi.Go();
            // Pastikan ada spasi sebelum variabel w agar query tidak "menempel"
            String Q = "SELECT * FROM barang " + w; 
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);

            while (R.next()) {
                // Ambil data sesuai nama kolom di database Anda
                String id = R.getString("id_barang");
                String nama = R.getString("nama_barang");
                String kategori = R.getString("kategori");
                String stok = R.getString("stok");

                // Ambil harga sebagai angka agar bisa diformat rapi
                double h_beli = R.getDouble("harga_beli");
                double h_jual = R.getDouble("harga_jual");

                String satuan = R.getString("satuan"); 
                String tgl = R.getString("tanggal_masuk");

                // Format angka (menghilangkan .00)
                String vBeli = String.format("%.0f", h_beli);
                String vJual = String.format("%.0f", h_jual);

                // Masukkan ke array sesuai urutan kolom JTable Anda
                Object[] databarang = {id, nama, kategori, stok, vBeli, vJual, satuan, tgl};
                model.addRow(databarang);
            }

        } catch (Exception e) {
            // Agar error terlihat di console NetBeans jika ada masalah
            e.printStackTrace(); 
            System.out.println("Error Load Data: " + e.getMessage());
        
            
        }
    }

    private void refreshDataproducts(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
