/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package motorin.panel;

import com.motorin.db.koneksi;
import com.motorin.db.User;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tito
 */
public class RiwayatTransaksi extends javax.swing.JPanel {
    
    DefaultTableModel model;

    /**
     * Creates new form RiwayatTransaksi
     */
    public RiwayatTransaksi() {
        initComponents();
        
        model = new DefaultTableModel();
        tblRiwayat.setModel(model);
        
       
        model.addColumn("ID Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Kasir (Pegawai)"); // Ini untuk Tugas 39/41
        model.addColumn("Total Belanja");
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Riwayat = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        label_Riwayat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_Riwayat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Riwayat.setText("Riwayat Transaksi Penjualan");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayat);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Riwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_Riwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_Riwayat;
    private javax.swing.JTable tblRiwayat;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        // Hapus data lama di tabel biar tidak menumpuk
        model.setRowCount(0);

        try {
            Connection K = koneksi.Go();
            Statement S = K.createStatement();

            String sql = "";

            // LOGIKA FILTER (Tugas 41):
            // Jika yang login ADMIN / MANAJER -> Lihat Semua Data
            // Jika yang login KASIR -> Cuma lihat data dia sendiri
            if (User.getJabatan().equalsIgnoreCase("admin") || User.getJabatan().equalsIgnoreCase("manajer")) {
                sql = "SELECT * FROM transaksi ORDER BY tanggal DESC";
            } else {
                // Kasir hanya lihat transaksinya sendiri
                sql = "SELECT * FROM transaksi WHERE nama_pegawai = '" + User.getNama() + "' ORDER BY tanggal DESC";
            }

            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                // Ambil data dari database
                String id = R.getString("id_transaksi");
                String tgl = R.getString("tanggal");
                String pel = R.getString("nama_pelanggan");
                String peg = R.getString("nama_pegawai");
                // Format harga jadi mata uang (Opsional, biar rapi)
                int total = R.getInt("total_harga");

                // Masukkan ke tabel
                Object[] data = {id, tgl, pel, peg, total};
                model.addRow(data);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error ambil data: " + e.getMessage());
        }
    }

}
