/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorindong;

import com.motorin.db.pegawai;
import motorin.panel.*;
import Dialog.Profile;
import javax.swing.JPanel;
import motorin.panel.GrafikPenjualan;
import motorin.panel.ProdukTerjual;
import motorin.panel.KinerjaKasir;
import motorin.panel.LaporanTerlaris;
import motorin.panel.LaporanHarian;
import motorin.panel.RiwayatTransaksi;
import motorin.panel.TotalLaba;
import motorin.panel.TotalPendapatan;


/**
 *
 * @author Tito
 */
public class DashboardManajer extends javax.swing.JFrame {
    // Ubah menjadi public agar bisa diakses dari LoginPage
    public com.motorin.db.pegawai P; 
    
    // ... sisa kode logger ...
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardManajer.class.getName());

    /**
     * Creates new form DashboardManajer
     */
    
    
    public DashboardManajer() {
        initComponents();
         
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void updateInfo() {
        if (P != null) {
            // Jika kamu ada label nama di design, buka komentar di bawah:
            // lblNamaManajer.setText("Manajer: " + P.getNama());
            
            System.out.println("Berhasil Login Sebagai: " + P.getNama());
        } else {
            System.out.println("Data Pegawai Kosong (Null)");
        }
    }
    
    private void AddViews(JPanel panel) {
        panelContent.removeAll(); // Menghapus isi panel tengah sebelumnya
        panelContent.setLayout(new java.awt.BorderLayout()); // Mengatur layout agar rapi
        panelContent.add(panel, java.awt.BorderLayout.CENTER); // Memasukkan panel laporan baru
        panelContent.revalidate(); // Memperbarui struktur komponen
        panelContent.repaint(); // Menggambar ulang tampilan agar muncul
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGrafik = new javax.swing.JButton();
        btnProdukTerjual = new javax.swing.JButton();
        btnkinerjakasir = new javax.swing.JButton();
        btnLpTerlaris = new javax.swing.JButton();
        btnLaporanHarian1 = new javax.swing.JButton();
        btnRiwayatTransaksi1 = new javax.swing.JButton();
        btnTotalLaba = new javax.swing.JButton();
        btnTotalPendapatan2 = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton2.setText("LogOut");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        jLabel2.setText("jLabel2");

        btnProfile.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.setBorder(null);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1358, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnGrafik.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnGrafik.setText("Laporan Grafik");
        btnGrafik.setBorder(null);
        btnGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafikActionPerformed(evt);
            }
        });

        btnProdukTerjual.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnProdukTerjual.setText("Produk Terjual");
        btnProdukTerjual.setBorder(null);
        btnProdukTerjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukTerjualActionPerformed(evt);
            }
        });

        btnkinerjakasir.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnkinerjakasir.setText("Kinerja Kasir");
        btnkinerjakasir.setBorder(null);
        btnkinerjakasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkinerjakasirActionPerformed(evt);
            }
        });

        btnLpTerlaris.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnLpTerlaris.setText("Laporan Terlaris");
        btnLpTerlaris.setBorder(null);
        btnLpTerlaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLpTerlarisActionPerformed(evt);
            }
        });

        btnLaporanHarian1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnLaporanHarian1.setText("Laporan Harian");
        btnLaporanHarian1.setBorder(null);
        btnLaporanHarian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanHarian1ActionPerformed(evt);
            }
        });

        btnRiwayatTransaksi1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnRiwayatTransaksi1.setText("Riwayat Transaksi");
        btnRiwayatTransaksi1.setBorder(null);
        btnRiwayatTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatTransaksi1ActionPerformed(evt);
            }
        });

        btnTotalLaba.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnTotalLaba.setText("Total Laba");
        btnTotalLaba.setBorder(null);
        btnTotalLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalLabaActionPerformed(evt);
            }
        });

        btnTotalPendapatan2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        btnTotalPendapatan2.setText("Total Pendapatan");
        btnTotalPendapatan2.setBorder(null);
        btnTotalPendapatan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPendapatan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGrafik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLpTerlaris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdukTerjual, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(btnkinerjakasir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(btnTotalLaba, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(btnTotalPendapatan2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnLaporanHarian1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnRiwayatTransaksi1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnLpTerlaris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrafik)
                .addGap(55, 55, 55)
                .addComponent(btnProdukTerjual)
                .addGap(64, 64, 64)
                .addComponent(btnTotalPendapatan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTotalLaba)
                .addGap(18, 18, 18)
                .addComponent(btnkinerjakasir)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(btnLaporanHarian1)
                    .addContainerGap(545, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(btnRiwayatTransaksi1)
                    .addContainerGap(446, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginPage P = new LoginPage();
        this.setVisible(false);
        P.setVisible(true);
        P.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        Profile pl = new Profile(null,true);
        pl.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafikActionPerformed

        AddViews(new GrafikPenjualan());
    }//GEN-LAST:event_btnGrafikActionPerformed

    private void btnProdukTerjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukTerjualActionPerformed
        AddViews(new ProdukTerjual());
    }//GEN-LAST:event_btnProdukTerjualActionPerformed

    private void btnkinerjakasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkinerjakasirActionPerformed
        AddViews(new KinerjaKasir());
    }//GEN-LAST:event_btnkinerjakasirActionPerformed

    private void btnLpTerlarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLpTerlarisActionPerformed
        AddViews(new LaporanTerlaris());
    }//GEN-LAST:event_btnLpTerlarisActionPerformed

    private void btnLaporanHarian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanHarian1ActionPerformed
        AddViews(new LaporanHarian());
    }//GEN-LAST:event_btnLaporanHarian1ActionPerformed

    private void btnRiwayatTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatTransaksi1ActionPerformed
        AddViews(new RiwayatTransaksi());
    }//GEN-LAST:event_btnRiwayatTransaksi1ActionPerformed

    private void btnTotalLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalLabaActionPerformed
        AddViews(new TotalLaba());
    }//GEN-LAST:event_btnTotalLabaActionPerformed

    private void btnTotalPendapatan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPendapatan2ActionPerformed
        AddViews(new TotalPendapatan() );
    }//GEN-LAST:event_btnTotalPendapatan2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardManajer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafik;
    private javax.swing.JButton btnLaporanHarian1;
    private javax.swing.JButton btnLpTerlaris;
    private javax.swing.JButton btnProdukTerjual;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRiwayatTransaksi1;
    private javax.swing.JButton btnTotalLaba;
    private javax.swing.JButton btnTotalPendapatan2;
    private javax.swing.JButton btnkinerjakasir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
